# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 259ec7444cdf58a630e474f7e00d162571ba1f0a5b04297081a68f7f7f19a79bd14cb8ea42f7b1ae7fac5f4b5764fc7c14987e584d818731d5328ac400840d7a

test:
  secret_key_base: 89640be8e37d519b685b82026bc2d89a29de7638408ce35de9e7303469f0212586f76ef9002111ec2fd1fd43176c102673907ec58864a4d2ce7ed1bf2a20926a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
